// <auto-generated />
namespace CV_Siten.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class testingnew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testingnew));
        
        string IMigrationMetadata.Id
        {
            get { return "202112301550063_testing new"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
